SIGECA_Shop/Controllers/CarritoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SIGECA_Shop.Models;
using SIGECA_Shop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SIGECA_Shop.Helpers;

namespace SIGECA_Shop.Controllers
{
    public class CarritoController : Controller
    {
        private readonly VentaService _ventaService;
        private readonly ProductoService _productoService;

        public CarritoController(VentaService ventaService, ProductoService productoService)
        {
            _ventaService = ventaService;
            _productoService = productoService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> RegistrarVenta([FromBody] Venta venta)
        {
            List<Venta> ventas = await _ventaService.GetAll();
            int record = ventas.Count;
            string codigo = "V-" + Convert.ToString(record + 1).PadLeft(6, '0');
            venta.codigoVenta = codigo;
            List<Producto> productos = await _productoService.GetAll();
            Object result = null;
            try
            {
                venta.fechaVenta = DateTime.Now;
                venta = (Venta)await _ventaService.CreateVenta(venta);
                result = new { result = "success", title = "Satisfactorio", message = "Venta Registrado Correctamente",value=venta, url = "Carrito/Registro" };
                string Htmlbody = Resource.HtmlEnvioCorreo;
                Htmlbody = Htmlbody.Replace("#NOMBRE#", venta.datos.nombres);
                Htmlbody = Htmlbody.Replace("#APELLIDO#", venta.datos.apellidos);
                Htmlbody = Htmlbody.Replace("#CODVENTA#", venta.codigoVenta);
                Htmlbody = Htmlbody.Replace("#TOTAL#","S/. "+ venta.total.ToString("0.00"));
                string productosHTML = string.Empty;
                foreach (ItemsVenta prod in venta.items)
                {
                    Producto prodtemp = productos.Find(x => x.id == prod.productoID);
                    productosHTML += "<tr>";
                    productosHTML += "<td width='75%' align='left' style='font - family: Open Sans, Helvetica, Arial, sans-serif; font - size: 16px; font - weight: 400; line - height: 24px; padding: 15px 10px 5px 10px;'>" + prodtemp.nombre + " ( " + prod.cantidad + " ) " + "</td>";
                    productosHTML += "<td width='25 %' align='left' style='font - family: Open Sans, Helvetica, Arial, sans-serif; font - size: 16px; font - weight: 400; line - height: 24px; padding: 15px 10px 5px 10px;'>" +"S/. " +prod.subTotal.ToString("0.00") + "</td>";
                    productosHTML += "</tr>";
                    prodtemp.stock = prodtemp.stock - prod.cantidad;
                    await _productoService.UpdateProductoStock(prodtemp);
                }
                Htmlbody = Htmlbody.Replace("#PRODUCTOS#", productosHTML);
                await Helpers.Email.SendMail_Gmail(venta.datos.correo, "Su venta con el codigo " + venta.codigoVenta + " en Avicola Nancy, ha sido satisfactoria",Htmlbody);
                return Content(JsonConvert.SerializeObject(result));
            }
            catch (Exception ex)
            {
                result = new { result = "error", title = "Error", message = "Lo sentimos, hubo un problema no esperado. Vuelva a intentar por favor. " + ex.Message, url = "" };
                return Content(JsonConvert.SerializeObject(result));
            }
        }
    }
}

SIGECA_Shop/Controllers/TrackingController.cs
using Microsoft.AspNetCore.Mvc;
using SIGECA_Shop.Models;
using SIGECA_Shop.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;

namespace SIGECA_Shop.Controllers
{
    public class TrackingController : Controller
    {
        private readonly VentaService _ventaService;
        private readonly UsuarioService _usuarioService;
        private readonly ProductoService _productoService;
        public TrackingController(VentaService ventaService, UsuarioService usuarioService, ProductoService productoService)
        {
            _ventaService = ventaService;
            _usuarioService = usuarioService;
            _productoService = productoService;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> ObtenerProductoPorId(string productoID)
        {
            Object result = null;
            Venta venta = await _ventaService.GetByCodigoVenta(productoID);
            if (venta == null)
            {
                result = new { result = "error" };
                return Content(JsonConvert.SerializeObject(result));
            }
            List<Producto> productos = new List<Producto>();
            for (int i = 0; i < venta.items.Count; i++)
            {
                Producto producto = new Producto();
                producto = await _productoService.GetById(venta.items[i].productoID);
                productos.Add(producto);
            }
            result = new { result = "success", title = "Satisfactorio", value = new { venta, productos }, url = "Tracking/Consultar" };
            return Content(JsonConvert.SerializeObject(result));
        }
        public class ModelTracking
        {
            public IEnumerable<Usuario> usuario { get; set; }
            public IEnumerable<Venta> venta { get; set; }
            public IEnumerable<Producto> productos { get; set; }
        }
    }
}

SIGECA_Shop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Avícola Nancy</title>
    <link rel="shortcut icon" type="image/x-icon" href="https://scontent.flim17-1.fna.fbcdn.net/v/t1.6435-9/100478055_109763644085090_947251463720009728_n.jpg?_nc_cat=103&ccb=1-3&_nc_sid=973b4a&_nc_ohc=fUxXxzNSj0oAX-ET2wy&_nc_ht=scontent.flim17-1.fna&oh=d1823d50a47f8cef491dcae96f18deb4&oe=60D69D68">
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/owl.carousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/vendor/venobox/venobox.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <!--Icons CSS File-->
    <link href="~/assets/vendor/icofont/icofont.min.css" rel="stylesheet" />
    <link href="~/assets/vendor/boxicons/css/animations.css" rel="stylesheet" />
    <link href="~/assets/vendor/boxicons/css/boxicons.css" rel="stylesheet" />
    <link href="~/assets/vendor/boxicons/css/transformations.css" rel="stylesheet" />
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">


    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    @{
        /*var str = HttpContextAccessor.HttpContext.Session.GetString("isFiltered");
        var obj = JsonConvert.DeserializeObject<UsuarioDTO>(str);*/
    }
    <header id="header" class="">
        <div class="container d-flex align-items-center">

            <a class="logo mr-auto d-flex align-items-center" href="/">
                <img src="~/assets/img/avicola2.jpg"
                     class="d-inline-block align-top mr-3 rounded-circle" alt="Avicola Nancy">
                <b>Avícola Nancy</b>
            </a>
            <nav class="nav-menu d-none d-lg-block">
                <ul>
                    <li class="@ViewBag.HomeActivate"><a asp-controller="Home" asp-action="Index">Inicio</a></li>
                    <li id="catalogMenu"><a asp-controller="Home" asp-action="Index" asp-fragment="catalog">Catálogo</a></li>
                    @*<li><a href="#menu">Menu</a></li>
        <li><a href="#specials">Specials</a></li>
        <li><a href="#events">Events</a></li>
        <li><a href="#gallery">Gallery</a></li>*@
                    <li id="contactMenu"><a asp-controller="Home" asp-action="Index" asp-fragment="contact">Contacto</a></li>
                    <li id="aboutMenu"><a asp-controller="Home" asp-action="Index" asp-fragment="about">Acerca de</a></li>
                    <li id="aboutMenu"><a asp-controller="Tracking" asp-action="Index">Seguimiento <i class="fas fa-search"></i></a></li>
                    <li id="carritoMenu"><a style="text-decoration:none" asp-controller="Carrito" asp-action="Index"><i class="fas fa-cart-plus"></i><span style="padding-left:4px" id="contadorItems">0</span></a></li>

                    @*<li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle d-flex align-items-center align-middle" id="userDropdown" role="button"
               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="bx bxs-user  mr-2"></i>
                Ricardo Arbildo J.
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                 aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="bx bx-user"></i>
                    Mi Perfil
                </a>
                <a class="dropdown-item" href="#">
                    <i class="icofont-ssl-security"></i>
                    Cambiar Contraseña
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                    <i class="bx bx-log-out"></i>
                    Cerrar Sesión
                </a>
            </div>
        </li>

        <li><a href="#car"><h3><i class="bx bxs-cart-alt"></i></h3></a></li>*@

                    @*@if (ViewBag.Inicio)
                    {

                        @if (true)
                        {
                            <li class="book-a-table text-center"><a asp-controller="Home" asp-action="Login">Iniciar Sesión</a></li>
                        }
                        else
                        {
                            <li class="nav-item dropdown no-arrow">
                                <a class="nav-link dropdown-toggle d-flex align-items-center align-middle" id="userDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bx bxs-user  mr-2"></i>
                                    Ricardo Arbildo J.
                                </a>
                                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                     aria-labelledby="userDropdown">
                                    <a class="dropdown-item" href="#">
                                        <i class="bx bx-user"></i>
                                        Mi Perfil
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="icofont-ssl-security"></i>
                                        Cambiar Contraseña
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                        <i class="bx bx-log-out"></i>
                                        Cerrar Sesión
                                    </a>
                                </div>
                                 Dropdown - User Information 
                            </li>

                            <li><a href="#car"><h3><i class="bx bxs-cart-alt"></i></h3></a></li>
                        }
                    }*@
                    @*else
        {
            <li class="@ViewBag.LoginActivate"><a asp-controller="Home" asp-action="Login">Iniciar Sesión</a></li>
        }*@



                    @*<li class="book-a-table text-center"><a href="#book-a-table">Book a table</a></li>*@
                </ul>
            </nav>


        </div>
        <button type="button" class="mobile-nav-toggle d-lg-none"><i class="icofont-navigation-menu"></i></button>
    </header>

    @if (true)
    {

    }

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer id="footer" >

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Avícola Nancy</span></strong>. Todos los Derechos Reservados
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/restaurantly-restaurant-template/ -->
                Designed by <a href="https://bootstrapmade.com/">SIGECA</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top"><i class="bx bx-up-arrow-alt"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/jquery/jquery.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/jquery.easing/jquery.easing.min.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/owl.carousel/owl.carousel.min.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/venobox/venobox.min.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Template Main JS File -->
    <script src="~/js/Carrito/Counter.js"></script>
    <script src="~/assets/js/main.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>